### ISSUE TITLE
[MSSQL] N+1 issue on reading messages

### ISSUE THREAD

**Issue by mihasic** [SQLStreamStore/SQLStreamStore#112]
Each read action is followed by FilterExpired() that tries to get the max age out of stream metadata. There is an internal cache, but it's not getting much hits.

Proposed fix: put latest metadata on a stream itself (including MaxAge and MaxCount) and read them together with regular message read action.

Possible workaround: unseal the MsSqlStreamStore, so in consumer code - GetStreamMetadataInternal can be overridden to avoid the Sql query (so Max age won't be supported)

**Comment by damianh** [comment]
This is not a N+1 issue but potentially a 2N one. SSS as a lib, doesn't have a background savaging process. Instead it lazily cleans up streams that have `MaxAge` and\or `MaxCount` metadata applied. Checking this metadata as streams are read via ReadAll is where the performance issue arise.... Current implementation is the metadata is read from the stream's metadata stream. This is effectively a double read if there are a large number of streams with small number of messages in them.

Since MaxAge and MaxCount are core metadata concepts, an optimization where by they are stored in the `Streams` table would help a lot here. (Clean up is actually done as a background task). This however is a breaking schema change for MS SQL.
