### ISSUE TITLE
Why should I use  SQLStreamStore instead of simple SQL implementation?

### ISSUE THREAD

**Issue by MNF** [SQLStreamStore/SQLStreamStore#179]
Our team wants to implement Event Store. I proposed to use  SQLStreamStore library. 
But our architect is asking, what are the benefits  of using the library compare to simple SQL implementation:
```
Insert  new messages  to SQL table with auto-incremental identity key 
and read from the table  page of records starting from specified identity key value
with optional filter of streamId
```

Note that we will use Azure sql database, so support of multiple types of databases is not important for us.

 What would you answer for such question? Which advantages of using of the library can I give?

Sorry, if the question is offensive for you. Hopefully the answer could be added to your documentation.

**Comment by ErazerBrecht** [comment]
We had the same question by someone in our team.

We are coming from EventStore by Greg Young. 
The reason we are migrating to a SQL backed EventStore is because the performance of EventStore in Docker is lacking in our environment... (And also it doesn't work well together with Istio). 

Totally unexpected I saw this library. Because the API is very similar with EventStore. It's really easy to change our current code.

But why didn't we do it ourself? The main reason was the 'subscription' part. We didn't have the time to implement it our own.

And we really needed that in our (CQRS) architecture...

**Comment by damianh** [comment]
@MNF No offense taken. It's a very reasonable question particularly for something that is going to a core dependency in your application. 

I'm not going to try to convince you either way; you'll need make up your own evaluation. SQLStreamStore has features (different concurrency models, idempotent appends, metadata, subscriptions, deletion tracking etc) - do you need these or not? We've all built a-queue-in-a-db before and it's easy to do a simple stream / event store too. Philosophically I think building one's own store is a good exercise if for nothing else other than learning some mechanical apathy. Also, will learn that `auto-incremental identity keys` are neither gapless nor guarantees ordering (hopefully before production) ;) 

The #sql-stream-store channel on the ddd-cqrs-es slack is the preferred place for these sort of discussions.

Cheers.
