### ISSUE TITLE
store.CreateSchema should ignore errors “index  already exists”

### ISSUE THREAD

**Issue by MNF** [SQLStreamStore/SQLStreamStore#217]
My application is running as 2 docker pods on 2 kubernetes clusters (4 instances total) and   uses MsSqlStreamStore to save to Azure SQL database.
I am using not modified versions from NuGet
 ```
<PackageReference Include="SqlStreamStore" Version="1.1.2" />
    <PackageReference Include="SqlStreamStore.MsSql" Version="1.1.2" />
```
On start of the service I am calling store.CreateSchema in case if it is the first time connecting  to a new database.
Under the heavy load during access to existing database (with existing schema) we’ve got hundreds of errors  
"an index or statistics with name 'IX_Streams_Id' already exists on table 'Streams'" and “an index or statistics with name 'IX_Messages_Position' already exists on table 'dbo.Messages’”.
I’ve reviewed the sql commands and they looks correct. But it seems that when having some issues with the database the code doesn’t understand that the indexes already exist and tries to create them again. 
I am able to workaround such errors by checking in catch for specific error messages

 ```
var store = new MsSqlStreamStore(settings);
                try
                {
                    await store.CreateSchema(); //if not exists
                }
                catch (SqlException e)
                {
                    if(e.Message.Contains("an index or statistics with name 'IX_Streams_Id' already exists on table 'Streams'",StringComparison.OrdinalIgnoreCase)
                        || e.Message.Contains("The operation failed because an index or statistics with name 'IX_Messages_Position' already exists", StringComparison.OrdinalIgnoreCase) // on table 'dbo.Messages' OR  on table 'Messages'
                       )
                    {
                        _logger.LogInformation(e,"Ignore the error, as we need  to create schema only once " +e.Message);
                    }
                    else
                    {
                        throw;
                    }
                }
```

1.I would suggest to include similar try/catch inside store.CreateSchema to apply the workaround to all users of the library.
	2. Do you have better explanation, how such errors generated?
	3. Please consider to rename CreateSchema() to CreateSchemaIfNotExists.

**Comment by damianh** [comment]
My original intention for `CreateSchema` to be called is at deployment time because, typically, DDL operations occur with a connection string with an user who has elevated privileges (i.e. DBA leve). And normal DML operations are with a restricted user. I've heard this protected against application being compromised and then being able to destructive operations on the database (I'm not 100% convinced).

The create schema code does not create a schema if it does not exist as you can see:

https://github.com/SQLStreamStore/SQLStreamStore/blob/20cef75ad027485bd314d105e527219f6b43568d/src/SqlStreamStore.MsSql/MsSqlStreamStoreV3.cs#L87-L94

What looks like what is happening is a race condition between your 4 instances starting up at the same time. They all see the schema doesn't exists and then they all try to create it. If so, to me that doesn't feel like the right way to do schema modification (or schema deployments). I'm going to advise you to have the `CreateSchema` call done from a single place.

> Please consider to rename CreateSchema() to CreateSchemaIfNotExists.

I'll do that for MsSqlStreamStoreV3 as it's still beta and thus not a breaking change. Add some additional comment.

Am going to leave the issue open if you have any further thoughts or my assumptions are incorrect.

**Comment by damianh** [comment]
Got a second on this and I'm happy with advising that `CreateSchema()` should be a one time / deploy / upgrade thing as designed. However, if you wish to perform the multiple concurrent attempts to create a schema you have a work around. This is not something I feel like I want to support (and test & maintain) in the library.
